### ISSUE TITLE
Cloudflare hybrid rendering support

### ISSUE THREAD

**Issue by jakobnoergaard** [danielroe/nuxt-vercel-isr#5]
Hey, thanks for all the cool work you guys are releasing!!!!

Is it correctly understood that hybrid rendering is currently not possible using Cloudflare (instead of Netlify or Vercel)? 
I have looked everywhere online and can't find any examples. 

I hope you can help with a quick answer.

**Comment by danielroe** [comment]
It is absolutely possible - it would even be zero config when you deploy to Cloudflare Pages
